package Userinterfaces.Graphic;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Controller.MainController;
import Model.RTProcess;
import Userinterfaces.ProcessFileParser;

import java.awt.Dimension;
import java.io.File;
import java.util.ArrayList;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author lopez
 */
public class ProcessFileChooserDialog extends javax.swing.JDialog {

    private Dimension initialSize;
    private File loadedFile;
    private ArrayList<Process> loadedProcesses;
    private MainController controller;

    /**
     * Creates new form ProcessFileChooserDialog
     */
    public ProcessFileChooserDialog(java.awt.Frame parent, boolean modal, MainController controller) {
        super(parent, modal);
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    public void initComponents() {

        processFileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione archivo de procesos");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        processFileChooser.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        processFileChooser.setApproveButtonText("Cargar definición de procesos");
        processFileChooser.setApproveButtonToolTipText("");
        processFileChooser.setDialogTitle("");
        processFileChooser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        processFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processFileChooserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Selecciones el archivo que contiene los procesos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(processFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(processFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void processFileChooserActionPerformed(java.awt.event.ActionEvent evt) {
        this.loadedFile = this.processFileChooser.getSelectedFile();
        this.readProcesses();
    }

    public void readProcesses() {
        try {
            controller.getProcesses().clear();
            for (RTProcess process :
                    ProcessFileParser.parsefile(this.processFileChooser.getSelectedFile().getPath())) {
                this.controller.addProcess(process);
            }
            showMessageDialog(this, "Archivo cargado");
            this.setVisible(false);
            System.out.println("Varas cargadas");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public ArrayList<Process> getLoadedProcesses() {
        return this.loadedProcesses;
    }

    private void formComponentResized(java.awt.event.ComponentEvent evt) {
        if(this.initialSize != null) this.setSize(initialSize);
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFileChooser processFileChooser;
    // End of variables declaration
}

