package Userinterfaces.Graphic;

import Controller.MainController;
import Model.Config;
import Model.RTProcess;

import javax.swing.*;

public class Window extends javax.swing.JFrame {

    MainController controller = new MainController();
    ProcessFileChooserDialog fileChooserDialog;
    TimelineDialog timelineDialog;
    RTProcessDisplayDialog processDisplayDialog;

    /**
     * Creates new form Window
     */
    public Window() {
        fileChooserDialog = new ProcessFileChooserDialog( this, true, controller);
        fileChooserDialog.initComponents();
        Config newConfig = new Config();
        newConfig.algorithm = Config.ScheduleAlgorithm.EDF;
        controller.setConfig(newConfig);
        initComponents();
        timelineDialog = new TimelineDialog(this, false);
        processDisplayDialog = new RTProcessDisplayDialog(this, false);
        this.earliestDeadlineRadioButton.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        algorithmBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        examineProcessesBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        periodSpinner = new javax.swing.JSpinner();
        idSpinner = new javax.swing.JSpinner();
        executionTimeSpinner = new javax.swing.JSpinner();
        deadlineSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        rateMonotonicRadioButton = new javax.swing.JRadioButton();
        earliestDeadlineRadioButton = new javax.swing.JRadioButton();
        viewProcessesBtn = new javax.swing.JButton();
        startSimulationBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        timelineLengthSpinner = new javax.swing.JSpinner();
        addProcessBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Elegir archivo de procesos:");

        examineProcessesBtn.setText("Examinar...");
        examineProcessesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examineProcessesBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresar procesos manualmente:");

        jLabel3.setText("Id:");

        jLabel4.setText("Ciclo:");

        jLabel5.setText("T.Ejecución:");

        jLabel6.setText("Dead Line:");

        jLabel7.setText("Algoritmo a usar:");

        algorithmBtnGroup.add(rateMonotonicRadioButton);
        rateMonotonicRadioButton.setText("Rate monotonic");
        rateMonotonicRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateMonotonicRadioButtonActionPerformed(evt);
            }
        });

        algorithmBtnGroup.add(earliestDeadlineRadioButton);
        earliestDeadlineRadioButton.setText("Earliest deadline first");
        earliestDeadlineRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earliestDeadlineRadioButtonActionPerformed(evt);
            }
        });

        viewProcessesBtn.setText("Ver procesos");
        viewProcessesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProcessesBtnActionPerformed(evt);
            }
        });

        startSimulationBtn.setText("Iniciar simulación");
        startSimulationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSimulationBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Tiempo de simulación:");

        timelineLengthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                timelineLengthSpinnerStateChanged(evt);
            }
        });

        addProcessBtn.setText("Añadir");
        addProcessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProcessBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(44, 44, 44)
                                                .addComponent(examineProcessesBtn))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(rateMonotonicRadioButton)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(earliestDeadlineRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(timelineLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(25, 25, 25)
                                                        .addComponent(viewProcessesBtn)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(startSimulationBtn)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(addProcessBtn)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(idSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(periodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(executionTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(deadlineSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6))))))
                                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(examineProcessesBtn))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(periodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(executionTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deadlineSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addProcessBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rateMonotonicRadioButton)
                                        .addComponent(earliestDeadlineRadioButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(timelineLengthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewProcessesBtn)
                                        .addComponent(startSimulationBtn))
                                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>

    private void examineProcessesBtnActionPerformed(java.awt.event.ActionEvent evt) {
        fileChooserDialog.setVisible(true);
    }

    private void rateMonotonicRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        controller.getConfig().algorithm = Config.ScheduleAlgorithm.RMS;
        controller.setConfig(controller.getConfig());
    }

    private void earliestDeadlineRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        controller.getConfig().algorithm = Config.ScheduleAlgorithm.EDF;
        controller.setConfig(controller.getConfig());
    }

    private void viewProcessesBtnActionPerformed(java.awt.event.ActionEvent evt) {
        processDisplayDialog.updateProcesses(controller.getProcesses());
        processDisplayDialog.setVisible(true);
    }

    private void addProcessBtnActionPerformed(java.awt.event.ActionEvent evt) {
        RTProcess newProcess = new RTProcess(
                ((Integer) periodSpinner.getValue()), ((Integer) deadlineSpinner.getValue()),
                ((Integer) executionTimeSpinner.getValue()), ((Integer) idSpinner.getValue())
        );
        this.controller.addProcess(newProcess);
    }

    private void timelineLengthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {
        this.controller.getConfig().timeLimit = (Integer) this.timelineLengthSpinner.getValue();
    }

    private void startSimulationBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            this.controller.reset();
            this.controller.updateTimeline();
            this.controller.schedule();
            this.timelineDialog.updateTimeline(this.controller.getTimeline());
            this.timelineDialog.setVisible(true);

            System.out.println("Calendarizo");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Hubo un error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Window dialog = new Window();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addProcessBtn;
    private javax.swing.ButtonGroup algorithmBtnGroup;
    private javax.swing.JSpinner deadlineSpinner;
    private javax.swing.JRadioButton earliestDeadlineRadioButton;
    private javax.swing.JButton examineProcessesBtn;
    private javax.swing.JSpinner executionTimeSpinner;
    private javax.swing.JSpinner idSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner periodSpinner;
    private javax.swing.JRadioButton rateMonotonicRadioButton;
    private javax.swing.JButton startSimulationBtn;
    private javax.swing.JSpinner timelineLengthSpinner;
    private javax.swing.JButton viewProcessesBtn;
    // End of variables declaration
}
